const { Client } = require('pg');

const key = 'liltamal696';
const projectRef = 'szcpihgltvewnlrzydpe';
const regions = [
  'us-west-1', 'us-east-1', 'us-east-2',
  'eu-west-1', 'eu-west-2', 'eu-west-3',
  'eu-central-1', 'eu-central-2',
  'eu-north-1', 'eu-south-1', 'eu-south-2',
  'ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3',
  'ap-southeast-1', 'ap-southeast-2', 'ap-southeast-3',
  'ap-south-1', 'ap-south-2',
  'sa-east-1',
  'ca-central-1',
  'me-south-1', 'me-central-1',
  'af-south-1',
];

async function tryRegion(region) {
  const c = new Client({
    host: `aws-0-${region}.pooler.supabase.com`,
    port: 6543,
    database: 'postgres',
    user: `postgres.${projectRef}`,
    password: key,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 8000,
  });
  try {
    await c.connect();
    console.log(`Connected via ${region}!`);
    await c.query(`SELECT 1`);
    return c;
  } catch (e) {
    return null;
  }
}

async function run() {
  for (const r of regions) {
    const c = await tryRegion(r);
    if (c) {
      await c.query(`
CREATE TABLE IF NOT EXISTS public.manga_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE INDEX IF NOT EXISTS idx_manga_favorites_user ON public.manga_favorites(user_id);
ALTER TABLE public.manga_favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own manga favorites" ON public.manga_favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own manga favorites" ON public.manga_favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own manga favorites" ON public.manga_favorites FOR DELETE USING (auth.uid() = user_id);
`);
      console.log('Migration executed successfully!');
      await c.end();
      return;
    }
  }
  console.log('Could not connect to any region. Trying direct connection...');
  // Try direct IPv6 connection
  const c = new Client({
    host: `db.${projectRef}.supabase.co`,
    port: 5432,
    database: 'postgres',
    user: 'postgres',
    password: key,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 8000,
  });
  try {
    await c.connect();
    console.log('Connected directly!');
    await c.query(`
CREATE TABLE IF NOT EXISTS public.manga_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE INDEX IF NOT EXISTS idx_manga_favorites_user ON public.manga_favorites(user_id);
ALTER TABLE public.manga_favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own manga favorites" ON public.manga_favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own manga favorites" ON public.manga_favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own manga favorites" ON public.manga_favorites FOR DELETE USING (auth.uid() = user_id);
`);
    console.log('Migration executed successfully!');
    await c.end();
  } catch (e) {
    console.log('Direct connection failed:', e.message);
    console.log('\nCould not connect to database. Please run the SQL manually in the Supabase SQL Editor.');
  }
}

run().catch((e) => {
  console.error('Error:', e.message);
  process.exit(1);
});
