CREATE TABLE IF NOT EXISTS public.manga_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE INDEX IF NOT EXISTS idx_manga_favorites_user ON public.manga_favorites(user_id);
ALTER TABLE public.manga_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own manga favorites" ON public.manga_favorites;
CREATE POLICY "Users can view own manga favorites" ON public.manga_favorites FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own manga favorites" ON public.manga_favorites;
CREATE POLICY "Users can insert own manga favorites" ON public.manga_favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own manga favorites" ON public.manga_favorites;
CREATE POLICY "Users can delete own manga favorites" ON public.manga_favorites FOR DELETE USING (auth.uid() = user_id);
