CREATE TABLE IF NOT EXISTS public.manga_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  chapter_number NUMERIC NOT NULL,
  chapter_id TEXT NOT NULL,
  title TEXT,
  image TEXT,
  page INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id, chapter_number)
);

CREATE INDEX IF NOT EXISTS idx_manga_history_user ON public.manga_history(user_id);
CREATE INDEX IF NOT EXISTS idx_manga_history_anime ON public.manga_history(user_id, anilist_id);

ALTER TABLE public.manga_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own manga history" ON public.manga_history;
CREATE POLICY "Users can view own manga history" ON public.manga_history FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own manga history" ON public.manga_history;
CREATE POLICY "Users can insert own manga history" ON public.manga_history FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own manga history" ON public.manga_history;
CREATE POLICY "Users can update own manga history" ON public.manga_history FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own manga history" ON public.manga_history;
CREATE POLICY "Users can delete own manga history" ON public.manga_history FOR DELETE USING (auth.uid() = user_id);
