CREATE TABLE IF NOT EXISTS public.community_episodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anilist_id BIGINT NOT NULL,
  episode_number INT NOT NULL,
  title TEXT DEFAULT '',
  url TEXT NOT NULL,
  provider_name TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'latam' CHECK (language IN ('sub', 'dub', 'latam')),
  submitted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  votes INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(anilist_id, episode_number, url)
);

CREATE TABLE IF NOT EXISTS public.community_episode_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  episode_id BIGINT NOT NULL REFERENCES public.community_episodes(id) ON DELETE CASCADE,
  vote SMALLINT NOT NULL CHECK (vote IN (1, -1)),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, episode_id)
);

CREATE INDEX IF NOT EXISTS idx_community_ep_anime ON public.community_episodes(anilist_id, episode_number);
CREATE INDEX IF NOT EXISTS idx_community_ep_status ON public.community_episodes(status);
CREATE INDEX IF NOT EXISTS idx_community_ep_votes_ep ON public.community_episode_votes(episode_id);

ALTER TABLE public.community_episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_episode_votes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view approved episodes" ON public.community_episodes;
CREATE POLICY "Anyone can view approved episodes" ON public.community_episodes FOR SELECT USING (status = 'approved' OR auth.uid() = submitted_by);

DROP POLICY IF EXISTS "Authenticated users can submit episodes" ON public.community_episodes;
CREATE POLICY "Authenticated users can submit episodes" ON public.community_episodes FOR INSERT WITH CHECK (auth.role() = 'authenticated' AND status = 'pending');

DROP POLICY IF EXISTS "Users can delete own pending episodes" ON public.community_episodes;
CREATE POLICY "Users can delete own pending episodes" ON public.community_episodes FOR DELETE USING (auth.uid() = submitted_by AND status = 'pending');

DROP POLICY IF EXISTS "Anyone can view votes" ON public.community_episode_votes;
CREATE POLICY "Anyone can view votes" ON public.community_episode_votes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can vote" ON public.community_episode_votes;
CREATE POLICY "Users can vote" ON public.community_episode_votes FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can change vote" ON public.community_episode_votes;
CREATE POLICY "Users can change vote" ON public.community_episode_votes FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can remove vote" ON public.community_episode_votes;
CREATE POLICY "Users can remove vote" ON public.community_episode_votes FOR DELETE USING (auth.uid() = user_id);
