CREATE TABLE IF NOT EXISTS public.anime_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  image TEXT,
  status TEXT NOT NULL CHECK (status IN ('watching', 'completed', 'plan_to_watch')),
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE INDEX IF NOT EXISTS idx_anime_lists_user ON public.anime_lists(user_id);
CREATE INDEX IF NOT EXISTS idx_anime_lists_status ON public.anime_lists(status);
ALTER TABLE public.anime_lists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own anime lists" ON public.anime_lists;
CREATE POLICY "Users can view own anime lists" ON public.anime_lists FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own anime lists" ON public.anime_lists;
CREATE POLICY "Users can insert own anime lists" ON public.anime_lists FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own anime lists" ON public.anime_lists;
CREATE POLICY "Users can update own anime lists" ON public.anime_lists FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own anime lists" ON public.anime_lists;
CREATE POLICY "Users can delete own anime lists" ON public.anime_lists FOR DELETE USING (auth.uid() = user_id);
