CREATE TABLE IF NOT EXISTS public.anime_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE INDEX IF NOT EXISTS idx_anime_favorites_user ON public.anime_favorites(user_id);
ALTER TABLE public.anime_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own anime favorites" ON public.anime_favorites;
CREATE POLICY "Users can view own anime favorites" ON public.anime_favorites FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own anime favorites" ON public.anime_favorites;
CREATE POLICY "Users can insert own anime favorites" ON public.anime_favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own anime favorites" ON public.anime_favorites;
CREATE POLICY "Users can delete own anime favorites" ON public.anime_favorites FOR DELETE USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.anime_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 10),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE INDEX IF NOT EXISTS idx_anime_ratings_anime ON public.anime_ratings(anilist_id);
ALTER TABLE public.anime_ratings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anime ratings are public" ON public.anime_ratings;
CREATE POLICY "Anime ratings are public" ON public.anime_ratings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert own ratings" ON public.anime_ratings;
CREATE POLICY "Users can insert own ratings" ON public.anime_ratings FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own ratings" ON public.anime_ratings;
CREATE POLICY "Users can update own ratings" ON public.anime_ratings FOR UPDATE USING (auth.uid() = user_id);
