-- Admin users table
CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view admin list" ON public.admin_users;
CREATE POLICY "Admins can view admin list"
  ON public.admin_users FOR SELECT USING (true);

DROP POLICY IF EXISTS "First user can bootstrap" ON public.admin_users;
CREATE POLICY "First user can bootstrap"
  ON public.admin_users FOR INSERT WITH CHECK (
    NOT EXISTS (SELECT 1 FROM public.admin_users)
  );

DROP POLICY IF EXISTS "Only admins can manage admins" ON public.admin_users;
CREATE POLICY "Only admins can manage admins"
  ON public.admin_users FOR ALL USING (
    EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid())
  );

-- Grant admins full access to community_episodes
DROP POLICY IF EXISTS "Admins can manage episodes" ON public.community_episodes;
CREATE POLICY "Admins can manage episodes"
  ON public.community_episodes FOR ALL USING (
    EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid())
  );
