CREATE TABLE IF NOT EXISTS public.manga_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  image TEXT,
  status TEXT NOT NULL CHECK (status IN ('reading', 'completed', 'plan_to_read')),
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE INDEX IF NOT EXISTS idx_manga_lists_user ON public.manga_lists(user_id);
CREATE INDEX IF NOT EXISTS idx_manga_lists_status ON public.manga_lists(status);

ALTER TABLE public.manga_lists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own manga lists"
  ON public.manga_lists FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert manga lists"
  ON public.manga_lists FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own manga lists"
  ON public.manga_lists FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own manga lists"
  ON public.manga_lists FOR DELETE USING (auth.uid() = user_id);
