CREATE TABLE IF NOT EXISTS public.collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  is_public BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS public.collection_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES public.collections(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  media_type TEXT NOT NULL CHECK (media_type IN ('anime', 'manga')),
  note TEXT DEFAULT '',
  added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(collection_id, anilist_id, media_type)
);

CREATE INDEX IF NOT EXISTS idx_collections_user ON public.collections(user_id);
CREATE INDEX IF NOT EXISTS idx_collection_items_collection ON public.collection_items(collection_id);

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public collections are viewable"
  ON public.collections FOR SELECT USING (is_public OR auth.uid() = user_id);

CREATE POLICY "Users can create collections"
  ON public.collections FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own collections"
  ON public.collections FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own collections"
  ON public.collections FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Collection items viewable with collection"
  ON public.collection_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.collections WHERE id = collection_id AND (is_public OR auth.uid() = user_id))
  );

CREATE POLICY "Users can manage items in own collections"
  ON public.collection_items FOR ALL USING (
    EXISTS (SELECT 1 FROM public.collections WHERE id = collection_id AND auth.uid() = user_id)
  );
