CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anilist_id BIGINT NOT NULL,
  media_type TEXT NOT NULL DEFAULT 'anime' CHECK (media_type IN ('anime', 'manga')),
  score INT NOT NULL CHECK (score >= 1 AND score <= 10),
  content TEXT NOT NULL CHECK (char_length(content) >= 10 AND char_length(content) <= 5000),
  has_spoilers BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, anilist_id)
);

CREATE TABLE IF NOT EXISTS public.review_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  review_id BIGINT NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
  vote SMALLINT NOT NULL CHECK (vote IN (1, -1)),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, review_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_anime ON public.reviews(anilist_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_review_votes_review ON public.review_votes(review_id);
CREATE INDEX IF NOT EXISTS idx_reviews_recent ON public.reviews(created_at DESC);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_votes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Reviews are public" ON public.reviews;
CREATE POLICY "Reviews are public" ON public.reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can create reviews" ON public.reviews;
CREATE POLICY "Users can create reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own reviews" ON public.reviews;
CREATE POLICY "Users can update own reviews" ON public.reviews FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete own reviews" ON public.reviews;
CREATE POLICY "Users can delete own reviews" ON public.reviews FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Review votes are public" ON public.review_votes;
CREATE POLICY "Review votes are public" ON public.review_votes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can vote" ON public.review_votes;
CREATE POLICY "Users can vote" ON public.review_votes FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can change vote" ON public.review_votes;
CREATE POLICY "Users can change vote" ON public.review_votes FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can remove vote" ON public.review_votes;
CREATE POLICY "Users can remove vote" ON public.review_votes FOR DELETE USING (auth.uid() = user_id);
