CREATE TABLE IF NOT EXISTS public.community_novel_chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  novel_slug TEXT NOT NULL,
  chapter_number NUMERIC NOT NULL,
  title TEXT DEFAULT '',
  url TEXT NOT NULL,
  provider_name TEXT NOT NULL,
  submitted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  votes INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(novel_slug, chapter_number, url)
);

CREATE TABLE IF NOT EXISTS public.community_novel_chapter_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  chapter_id BIGINT NOT NULL REFERENCES public.community_novel_chapters(id) ON DELETE CASCADE,
  vote SMALLINT NOT NULL CHECK (vote IN (1, -1)),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, chapter_id)
);

ALTER TABLE public.community_novel_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_novel_chapter_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view approved novel chapters"
  ON public.community_novel_chapters FOR SELECT
  USING (status = 'approved' OR submitted_by = auth.uid());

CREATE POLICY "Auth users can insert novel chapters"
  ON public.community_novel_chapters FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can delete own pending novel chapters"
  ON public.community_novel_chapters FOR DELETE
  USING (submitted_by = auth.uid() AND status = 'pending');

CREATE POLICY "Anyone can read novel chapter votes"
  ON public.community_novel_chapter_votes FOR SELECT
  USING (true);

CREATE POLICY "Auth users can insert novel chapter votes"
  ON public.community_novel_chapter_votes FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admins can manage all novel chapters"
  ON public.community_novel_chapters FOR ALL
  USING (EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid()));

CREATE POLICY "Admins can manage all novel chapter votes"
  ON public.community_novel_chapter_votes FOR ALL
  USING (EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid()));
